### ISSUE TITLE
Direction to take the project

### ISSUE THREAD

**Issue by PSI-Rockin** [PSI-Rockin/DobieStation#1]
Note: all of this assumes that I continue working on DobieStation, which is not guaranteed.

I don't have any intention of overtaking PCSX2 or even providing any competition in PS2 land, but it'd be nice to have some sort of idea on where to go.

Currently, in order to get any homebrew working at all, I'll need to implement some CP0 stuff, the DMAC, and the GS (of which I'd want to create a software renderer). After that, it's getting the FPU and VUs in a basic state to run the other homebrew I've collected. I'll also need the IOP, especially for commercial games.

Commercial games will need an ISO loader, which shouldn't be too difficult. A dilemma, however: do I go the HLE route for the BIOS or the LLE route? Personally, I'd rather go LLE, but I don't know how much effort that requires. HLE seems like the simpler choice, but presents problems in the long run IMO.

Once I get some simple commercial games working... I dunno what to do next. I'll more than likely be burnt out by then, if I didn't give up before. I have CorgiDS to take care of, after all. But if not, I really don't know what I want to do with this. If anyone's reading this, some ideas would be helpful.

**Comment by Nobbs66** [comment]
The core IOP emulation should be rather simple to get up and running. If you ever want to support backwards compatibility, you'll want to consider implementing the GTE and PGIF as well. 

Keep in mind that the VUs and FPU are not IEEE 754 compliant, so accurately emulating those will likely be quite slow. It is also possible to implement something similar to the rounding and clamping modes in PCSX2 if speed is a concern. 

As for how to handle the BIOS, I think it would be best to just LLE it.

**Comment by PSI-Rockin** [comment]
My strategy for now is to just HLE the BIOS while I'm getting homebrew running (Currently, I'm working on the "3 Stars" demo). After I get commercial ISOs loading, then I'll go the LLE route so I won't have to reimplement the IOP modules.

I have indeed heard horror stories about how the PS2 handles floating-points... division by zero being routine procedure, off-by-one errors causing games to not boot, and more. I'll worry about handling that when I get there.

The more I think about it, the more I want to make an Android port for this. So speed will definitely be an issue. I'll perform all my testing on PC for now. We'll see about the Android idea once I get some fairly decent compatibility.

**Comment by PSI-Rockin** [comment]
As DobieStation has advanced considerably and now has clear short-term and long-term goals, this issue is unnecessary.
