### ISSUE TITLE
Consider using a popular IRC network (or Discord) for discussion

### ISSUE THREAD

**Issue by darkf** [PSI-Rockin/DobieStation#10]
You use `badnik.net` which (presumably) not many people use, and no incentive to join -- using Freenode or something more accessible like Discord (or even Matrix?) would probably help adoption.

**Comment by PSI-Rockin** [comment]
Since you've brought it up, doing so is something I may consider in the future. However, because DobieStation is so young, I highly doubt moving networks now would convince people to collaborate. People are going to care far more about emulator progress than choice of IRC network, in my opinion.

**Comment by darkf** [comment]
For sure, I only bring it up because I am reluctant to hop on more IRC networks, otherwise I would be lurking in it. :-)

**Comment by izik1** [comment]
Should this be closed (as solved) due to the changes to the readme made a few days ago?

**Comment by PSI-Rockin** [comment]
Indeed.
