### ISSUE TITLE
shift overflow?

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [PSI-Rockin/DobieStation#11]
Hi, 
at GraphicsSynthesizer::write32_privileged in src/core/gs.cpp, a variable "value" is uint32_t.
but there are  "value >> 32" and "value >> 43".  Is this correct?

**Comment by PSI-Rockin** [comment]
Ah, nice catch! I copied that code from write64_privileged and didn't think too much of it. The value >> 32 stuff should not be there. I'll provide a fix momentarily.

**Comment by PSI-Rockin** [comment]
Should be fixed as of f43493cdee19ccb2cf79ffa962344078eb57eac0
