### ISSUE TITLE
First beta release?

### ISSUE THREAD

**Issue by TechUtopiaYoutube** [PSI-Rockin/DobieStation#111]
Hello guys,
first time hearing for this project.
I am focused on emulators for Android OS.
Please email me as soon as you release pre official build.
So i Can test and promote this emulator.
wish ya all the best, hope this project gets more people involved..
TechUtopia

**Comment by PSI-Rockin** [comment]
I wouldn't expect the Android port to come out for at least a year, simply because there's still so much work to do on the PC side.
