### ISSUE TITLE
Wrong disassembly instruction returned for sub

### ISSUE THREAD

**Issue by GabrielRavier** [PSI-Rockin/DobieStation#116]
https://github.com/PSI-Rockin/DobieStation/blob/152164f1f44e69ffae52db62cde3b6279d786ff8/src/core/ee/emotiondisasm.cpp#L535 seems to return "add" for the sub instruction. This is probably wrong.

**Comment by PSI-Rockin** [comment]
Fixed as of https://github.com/PSI-Rockin/DobieStation/commit/704ec82126b2a7518c0326ab549a5298f784c1a1
