### ISSUE TITLE
High cpu load at idle

### ISSUE THREAD

**Issue by tadanokojin** [PSI-Rockin/DobieStation#150]
Dobiestation has an issue with cpu usage at idle.

On my machine that amounts to about 20-30% cpu usage just with no game loaded:
![002534](https://user-images.githubusercontent.com/26046960/54597147-6ff68280-4a0c-11e9-8661-aa256429f045.png)

A quick cpu profile will show the issue:
![002535](https://user-images.githubusercontent.com/26046960/54597257-a2a07b00-4a0c-11e9-8ba8-9361e6a71b5e.png)

![002536](https://user-images.githubusercontent.com/26046960/54597628-412cdc00-4a0d-11e9-8e03-964975bb35e6.png)

code is here:
https://github.com/PSI-Rockin/DobieStation/blob/67a9e2682c037af430ad42112687405551c99ef3/src/core/gsthread.cpp#L285-L288

possible solutions:
- using `std::thread::sleep_for` to sleep for some small amount of time
- using a condition variable to alert the gs thread when there is data to process

**Comment by refractionpcsx2** [comment]
The latter would probably be better, stop the thread just spinning

**Comment by water111** [comment]
I agree that a condition variable is the right thing to do here, but I'm worried about the overhead of a condition variable per GS message (I think it involves a syscall in Linux).  I think we're also losing some performance to pushing/popping so frequently from the GS_fifo - even though it's "lock-free" there's still some overhead to push/pop from different threads so rapidly.

**Comment by refractionpcsx2** [comment]
I'm not sure how Dobie does it, but I think on PCSX2 we build up a local buffer before pushing it to the thread, would that be a better way of doing it @water111 ?

**Comment by tadanokojin** [comment]
I believe it should be possible to sleep the EmuThread on a wait condition qt side and signal that when a game is loaded.

Perhaps there's a way to notify all threads when the emulation starts/stops.
That might be better than waiting for data with regards to overhead (if practical).

**Comment by water111** [comment]
@refractionpcsx2 That sounds like a good idea.  You could even double buffer so the emulator fills one buffer while the GS renders from another.  I'm about to open an issue for some performance stuff I've noticed - I think there are a few tweaks we can do to improve performance pretty easily.
