### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [PSI-Rockin/DobieStation#23]
Hi, I'm using gcc-7.3.1 on Fedora27.  The build fails with the error message below.

/home/hoge/DobieStation/src/core/sif.cpp: In member function 'void SubsystemInte
rface::write_SIF1(uint64_t*)':
/home/hoge/DobieStation/src/core/sif.cpp:33:5: error: 'printf' was not declared 
in this scope
     printf("[SIF1] Quad: $%08X_%08X_%08X_%08X\n", quad[1] >> 32, quad[1], quad[
0] >> 32, quad[0]);
     ^~~~~~
/home/hoge/DobieStation/src/core/sif.cpp:33:5: note: suggested alternative: 'int
'
     printf("[SIF1] Quad: $%08X_%08X_%08X_%08X\n", quad[1] >> 32, quad[1], quad[
0] >> 32, quad[0]);
     ^~~~~~
     int
make[2]: *** [CMakeFiles/DobieStation.dir/build.make:519: CMakeFiles/DobieStatio
n.dir/src/core/sif.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/DobieStation.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

Including stdio.h in src/core/sif.cpp can prevent the error.

**Comment by PSI-Rockin** [comment]
Strange, didn't catch that. I'll fix it when I get home, or you can send a quick PR. (Use cstdio, though)

Note that I'm currently working on making the BIOS boot, so you won't see any homebrew working without modifying the source.

**Comment by tokumeiwokiboushimasu** [comment]
Fixed.  Thanks.
