### ISSUE TITLE
Build fails on ArcoLinux:  ‘Background’ is not a member of ‘QPalette’

### ISSUE THREAD

**Issue by esotericDisciple** [PSI-Rockin/DobieStation#231]
...Even though pamac-manager shows Qt at version 5.13...

**Comment by tadanokojin** [comment]
Do you by change mean Arch? I've never heard of Arco.

**Comment by esotericDisciple** [comment]
ArcoLinux is a pre-made ArchLinux...though it builds in qt creator and the CmakeLists file...not sure what's going on with the qmake+.pro file...

**Comment by tadanokojin** [comment]
I use manjaro, I'll take a look at master when I get a moment.

**Comment by tadanokojin** [comment]
Was able to reproduce on manjaro. It appears looking at the docs qt had deprecated `QPalette::Background` in favor of `QPalette::Window`
https://doc.qt.io/qt-5/qpalette.html#ColorRole-enum

Bit odd it compiles with cmake just fine and I see nothing in the docs saying explicitly it was removed.
Anyway, replacing `QPalette::Background` will resolve the issue.

**Comment by tadanokojin** [comment]
Please test the PR when you get a moment.

**Comment by esotericDisciple** [comment]
ok will try to test today...I use manjaro on my non-nvidia hardware as then I don't have to deal with Arch/Manjaro directory differences issues...

**Comment by esotericDisciple** [comment]
Alright, it builds and runs now (following the qmake instructions)...

**Comment by tadanokojin** [comment]
Thank you
