### ISSUE TITLE
Project BIOS - getting the BIOS to boot successfully

### ISSUE THREAD

**Issue by PSI-Rockin** [PSI-Rockin/DobieStation#25]
This will be the "megaissue" for all BIOS problems until everything works.

As you may have seen, I've shifted my focus from compatibility for homebrew to getting the PS2 BIOS to work. I've implemented the IOP and some SIF/SBUS I/O registers, which has allowed the EE to progress in execution.

Now I'm facing some issues though... The EE is stuck in a loop waiting for a memory value to change, and I believe it's because it's waiting for an interrupt. The EE and IOP communicate through an RPC protocol using the SIF, which consists of dedicated DMA channels. This protocol is completely undocumented (as gamedevs didn't need to know about it), but my hypothesis on how it works is this:

1. The EE sends a command through the SIF1 DMAC channel.
2. The IOP receives data from its own SIF1 channel. When all data has been received, an interrupt is raised.
3. The interrupt handler on the IOP side executes this command and sends a reply through SIF0, another DMA channel.
4. The EE receives the reply through SIF0. Once this is done, an SIF0 interrupt is raised.

I'm currently having problems with step 3. The interrupt handler doesn't seem to process commands at all, and it's not sending a reply either. My most recent implementation (not committed yet) also doesn't invoke an interrupt at all, as the EE isn't sending its DMAtag for whatever reason. I'll keep looking for the cause of these problems.

**Comment by yoshi314** [comment]
is there any debugging facility so other people can take a look at this? (haven't compiled it yet, so i don't know).

**Comment by PSI-Rockin** [comment]
DobieStation includes a dual-purpose EE/IOP disassembler, but it outputs directly to the console. No other debugging tools exist at this time.

**Comment by PSI-Rockin** [comment]
I fixed the SIF problems. The key was adding DMAtags for the IOP as well as triggering interrupts on the first command instead of the last.

Now it's running into an issue where a semaphore's context isn't being initialized, which makes the program go haywire.

**Comment by PSI-Rockin** [comment]
Considering the BIOS actually boots successfully now, this can be closed.
