### ISSUE TITLE
Screenshots, videos?

### ISSUE THREAD

**Issue by brad2192** [PSI-Rockin/DobieStation#35]
Can't find a single video or image of this Emulator in action...

**Comment by Nobbs66** [comment]
It literally only boots two games. What do you expect

**Comment by refractionpcsx2** [comment]
And by "boots" he means shows 1 static screen from each.

**Comment by PSI-Rockin** [comment]
Screenshots will come as DobieStation becomes more compatible. For now though, this is not an issue.
