### ISSUE TITLE
Klonoa 2 works!

### ISSUE THREAD

**Issue by azoreseuropa** [PSI-Rockin/DobieStation#350]
FMV is about 19 fps and a little bit stuttering. In game is about 10 fps and a little but blurring and a few graphics error but didn't noticed. It is for macOS. Keep up the good work! Awesome!

**Comment by kenshen112** [comment]
https://docs.google.com/spreadsheets/d/1kPLMTBSB2xZ8Rar140jiLWNRqsLX9vlCx12PJS2H5aw/
If you want to see the general compatibility of DobieStation. Klonoa and several other's are known games to work quite well in DobieStation

**Comment by PSI-Rockin** [comment]
While I appreciate your kind comments, this GitHub should be used for general issues with the emulator, rather than specific compatibility reports. I suggest joining our Discord for discussions like this - it's on the README.

**Comment by azoreseuropa** [comment]
Yes, I already have you on my Discord and I will add to compatibility list once I test few games that are not on the list. Thank you! Keep up the good work! Can't wait!
