### ISSUE TITLE
Add list of required DLLs

### ISSUE THREAD

**Issue by mnadareski** [PSI-Rockin/DobieStation#38]
When building locally (Windows 10, MSYS2) and attempting to run the compiled program, many DLLs need to be copied to the runtime folder in order for the program to work properly. At a certain point, it stops naming the DLLs that need to be copied over and starts throwing a generic error. Can you list in the compile instructions exactly what DLLs are required for running the program?

**Comment by PSI-Rockin** [comment]
Copying DLLs won't work (last time I tried, it caused more errors to appear). If you don't have Qt installed on your system, you must get a build from someone else that has the required DLLs.

**Comment by mnadareski** [comment]
I may have not phrased that well. I do actually have Qt installed, and it explicitly lists the missing Qt DLLs when I go to run it. But it's the other DLLs, like the std C++ libs, that I'm having a hard time finding the entire list for.

**Comment by PSI-Rockin** [comment]
I'm on a Mac, so I don't know which DLLs are needed. If you're able to compile it, it should be running without problems (as it should link to the DLLs you have on your system). Which version of Qt do you have installed? Have you tried using Visual Studio? Others on Windows systems have been able to run DS just fine.

**Comment by mnadareski** [comment]
Using Dependency Walker, I have determined this (currently) exhaustive list of DLLs required by the MSYS2 build of DobieStation if you attempt to run it outside of the compile environment:

- libbz2-1.dll
- libfreetype-6.dll
- libgcc_s_seh-1.dll
- libglib-2.0-0.dll
- libgraphite2.dll
- libharfbuzz-0.dll
- libiconv-2.dll
- libicudt61.dll
- libicuin61.dll
- libicuuc61.dll
- libintl-8.dll
- libpcre-1.dll
- libpcre2-16-0.dll
- libpng16-16.dll
- libstdc++-6.dll
- libwinpthread-1.dll
- Qt5Core.dll
- Qt5Gui.dll
- Qt5Widgets.dll
- zlib1.dll

I hope this ends up as helpful for others with the same bizarrely specific environment and situation.

**Comment by nivel1** [comment]
Where i can found this dlls? 
libbz2-1.dll
libfreetype-6.dll
libgcc_s_seh-1.dll
libglib-2.0-0.dll
libgraphite2.dll
libharfbuzz-0.dll
libiconv-2.dll
libicudt61.dll
libicuin61.dll
libicuuc61.dll
libintl-8.dll
libpcre-1.dll
libpcre2-16-0.dll
libpng16-16.dll
libstdc++-6.dll
libwinpthread-1.dll
Qt5Core.dll
Qt5Gui.dll
Qt5Widgets.dll
zlib1.dll

**Comment by mnadareski** [comment]
They should be somewhere in your build environment. Usually something like a /lib folder
