### ISSUE TITLE
Nintendo Switch builds ? 

### ISSUE THREAD

**Issue by azoreseuropa** [PSI-Rockin/DobieStation#398]
I would love to test it. I test it on Mac/Pc and Klonoa 2 is playable but very slow.

**Comment by azoreseuropa** [comment]
Hello developer ? I waited for 7 days and no comments. ;)

**Comment by PSI-Rockin** [comment]
We have no plans to provide Switch builds at this time.

**Comment by azoreseuropa** [comment]
> We have no plans to provide Switch builds at this time.

Yeah, it is too early. Thanks.
