### ISSUE TITLE
Improved command line parsing

### ISSUE THREAD

**Issue by PSI-Rockin** [PSI-Rockin/DobieStation#40]
The current system for parsing command line options ([see here](https://github.com/PSI-Rockin/DobieStation/blob/cf6de8e230a953a4a492d760e659dd6ae4c0d807/src/qt/emuwindow.cpp#L60)) is hardcoded and quite ugly. This task is about making parsing more flexible and able to support multiple flags in the future.

**Comment by zwammetje** [comment]
If you're willing to use Qt 5.2 or higher for this project I can whip something up with QCommandLineParser. If you don't want Qt to handle this particular code or don't want that version requirement, I'll fix something up that only uses the standard library facilities of C++11.

Let me know and I'll implement something that's easy to extend during development and easy to use for the end-user.

**Comment by PSI-Rockin** [comment]
DobieStation uses Qt 5.9+, so the version wouldn't be an issue. I'm a bit torn about using QCommandLineParser though, as it might be a good idea to support other frontends in the future. I'd like to see a solution that doesn't rely on any third-party libraries.

**Comment by ZirconiumX** [comment]
Closed by #65?
