### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [PSI-Rockin/DobieStation#43]
Hi, on Fedora 27 (gcc-7.3.1), there is the following error.
Changing the 28th line of src/core/ee/ipu.hpp from

    const VLC_Entry entries[];

to

    const VLC_Entry *entries;

resolves the error.  But I don't know if it is correct solution.

[  2%] Automatic MOC for target DobieStation
[  2%] Built target DobieStation_autogen
Scanning dependencies of target DobieStation
[  5%] Building CXX object CMakeFiles/DobieStation.dir/src/core/ee/bios_hle.cpp.o
In file included from /home/aho/DobieStation/src/core/ee/../emulator.hpp:9:0,
                 from /home/aho/DobieStation/src/core/ee/bios_hle.cpp:5:
/home/aho/DobieStation/src/core/ee/../ee/ipu.hpp:28:29: error: flexible array member 'VLC_Table::entries' in an otherwise empty 'struct VLC_Table'
     const VLC_Entry entries[];
                             ^
make[2]: *** [CMakeFiles/DobieStation.dir/build.make:63: CMakeFiles/DobieStation.dir/src/core/ee/bios_hle.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/DobieStation.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by PSI-Rockin** [comment]
Oops, the VLC_Table struct is dead code; it doesn't need to be there at all. You can remove it in a PR if you'd like.

By the way, thanks for helping spot these build errors! I use clang, so it's not always easy to prevent these things.
