### ISSUE TITLE
Recommended system requirements?

### ISSUE THREAD

**Issue by InfamousKnight** [PSI-Rockin/DobieStation#444]
Any recommendated system requirements for this?

I have an i7 series core with Intel uhd 620. And my cpu runs at 1.8ghz and the games like midnight club 2 run at like 5fps when in game.

Would overclocking my cpu to 2.8 boost fps?

**Comment by feikname** [comment]
Hello,

There's a [_lot_](https://en.wikipedia.org/wiki/List_of_Intel_Core_i7_microprocessors) of i7 CPUs out there, you need to provide a more specific model. Please read [this How-To Geek article](https://www.howtogeek.com/413942/how-to-see-what-cpu-is-in-your-pc-and-how-fast-it-is/) on how to identify your CPU. Mine for example, is `i5-8250U`.

Please note that Dobie is **NOT** a ready emulator, this is still in early development so no matter how fast your PC some games simply won't run or will run very slowly. If you're looking for a more complete emulator try [PCSX2](https://pcsx2.net/).

Also, do you have no dedicated GPU? That's a very limiting factor in emulating PS2 games and could be the difference between 12FPS and that sweet 30FPS for some games.

Regarding the 1.8 GHz figure, I believe you have a mobile (notebook) CPU, right? If you're not, plase ignore what I will say next. 

These come with Intel's [Turbo Boost](https://en.wikipedia.org/wiki/Intel_Turbo_Boost) technology which allow the processor to overclock (or downclock!) automatically based on how heavy your usage. In Windows you can force the CPU to be always in its highest frequency (probably something from 3.4 GHz to 4.2 GHz depending on model) by clicking with left mouse button on battery icon and moving the slider all the way to the right in the "highest performance" setting and reverting it while you're not playing.

**Comment by InfamousKnight** [comment]
Here are my specs:
CPU: Quad Core Intel Core i7-8550U (-MT MCP-) 
speed/min/max: 800/400/4000 MHz Kernel: 5.4.0-42-generic x86_64 Up: 42m 
Mem: 1776.5/7845.6 MiB (22.6%) Storage: 931.51 GiB (33.1% used) Procs: 244 
Shell: bash 5.0.17 inxi: 3.0.38 


I'm not using this for casual gaming. I'm using it for this: https://github.com/TASVideos/BizHawk/issues/2250 I can live with 15-20fps. But like 2fps maybe not. Its recommended to use games that are low cpu hungry.

**Comment by zeromus** [comment]
Recommendated system requirements for dobiestation would not be relevant to bizhawk. We wildly butcher the emulators. Bothering the upstream devs with questions actually about bizhawk is the most effective method you have by making sure that bizhawk never has a good psx2 core since it just wastes everyone's time and makes the upstream devs resent our users. Make a tasvideo forum thread about this or something.

**Comment by PSI-Rockin** [comment]
While Dobie does have minimum requirements of a 64-bit CPU that supports SSE4.1, there are no recommended requirements as there are no computers strong enough to run Dobie at full speed currently. It will take a long time before Dobie is ready to be used for playing games.
