### ISSUE TITLE
Minor UI issue

### ISSUE THREAD

**Issue by HeroponRikiBestest** [PSI-Rockin/DobieStation#465]
The new UI has a minor issue; there's a seam that appears between the file name and the file size when you have it highlighted.
![image](https://user-images.githubusercontent.com/50224630/109567343-0a391f00-7a9a-11eb-9543-3e0fcc93e799.png)
however, it only displays while the window is selected; whenever you have the window deselected, it's gone.

**Comment by refractionpcsx2** [comment]
This has always been an issue, the window highlights the box you select, it will move side to side if you select the size or the name too.  The old UI did the same thing.

**Comment by HeroponRikiBestest** [comment]
Ah, alright, I think I just misunderstood how it worked. I think it would be better to have a solid, unbroken red when you select a game, but this definitely isn't an issue.
