### ISSUE TITLE
potential output_PRIM bug

### ISSUE THREAD

**Issue by StapleButter** [PSI-Rockin/DobieStation#5]
https://github.com/PSI-Rockin/DobieStation/blob/88fde3ec244691da7cbdf9abb7e3771b326637fc/DobieStation/gs.cpp#L350

this operation retains bit 46 of data[0]. you're then fitting it into a bool, which is going to be 32 bits or less. so unless the compiler adds an implicit conversion to bool, the value may be lost.

**Comment by PSI-Rockin** [comment]
There's more than one region of the code that converts 64-bit integers into bools like this. The specifications are unclear whether or not this is a problem, but it seems to imply that it's not. I'm keeping this up anyway in case it is.

**Comment by tokumeiwokiboushimasu** [comment]
A quick test with gcc-7.3.1 below shows that it is no problem (The output is 1).

#include<stdio.h>
int main(void) {
  bool a;
  long b;

  b = 1;
  b <<= 46;

  a = b;

  printf("%d\n", a);

  return 0;
}

**Comment by tokumeiwokiboushimasu** [comment]
It is OK too with clang-5.0.1.
