### ISSUE TITLE
i have a stupid idea and i know

### ISSUE THREAD

**Issue by amayra** [PSI-Rockin/DobieStation#57]
there any diff if you use PS2 emu in PS3 firmware instead of PS2 Bios ?

**Comment by refractionpcsx2** [comment]
If you can get it to work, no

**Comment by AcceptableSpare** [comment]
It's the same as a real ps2 minus networking support. It uses a japan dev 2.20 bios according to psdevwiki

**Comment by ijacquez** [comment]
Are you asking if you can use the BIOS from the PS3's PS2 emulator?
