### ISSUE TITLE
-skip doesn't work 

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [PSI-Rockin/DobieStation#66]
Hi, 
767af7e1b2950522ad9c4e14e2ae222c110d3b0d does not recognize -skip option.

**Comment by PSI-Rockin** [comment]
What happens if you try -s?

**Comment by tokumeiwokiboushimasu** [comment]
BIOS boots even when specify -s.

**Comment by tokumeiwokiboushimasu** [comment]
Oh, 
./Dobiestation -s scph10000.bin rom.iso
works.
./Dobiestation scph10000.bin rom.iso -s
doesn't work.  So, the order of options has changed?

**Comment by ZirconiumX** [comment]
The parser doesn't reorder options; in the first example, `-s` is an option; in the second, it's a positional argument that gets ignored.

**Comment by tokumeiwokiboushimasu** [comment]
ZirconiumX, I know it. But the previous version of Dobiestation admitted only the second case.
Anyway, I think it is better to implement -h option to print the usage.

**Comment by PSI-Rockin** [comment]
I fixed this problem on my local repo - you'll need to provide a -b flag for the BIOS and an -f flag for an optional ELF/ISO. However, this lets the flags be in any order you desire. I'll push my changes once I finish some work on the PS2 SPU

**Comment by tokumeiwokiboushimasu** [comment]
OK, now I close this issue.  Thanks.
