### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [PSI-Rockin/DobieStation#78]
The following error prevent the build.

/home/aho/DobieStation/src/core/gsthread.cpp:1572:87: warning: missing terminating ' character
     int32_t pix_v_step = stepsize((int32_t)v1.uv.v, v1.y, (int32_t)v2.uv.v, v2.y, 0x10'0000);
                                                                                       ^
/home/aho/DobieStation/src/core/gsthread.cpp:1572:87: error: missing terminating ' character
     int32_t pix_v_step = stepsize((int32_t)v1.uv.v, v1.y, (int32_t)v2.uv.v, v2.y, 0x10'0000);
                                                                                       ^~~~~~~
/home/aho/DobieStation/src/core/gsthread.cpp:1574:87: warning: missing terminating ' character
     int32_t pix_u_step = stepsize((int32_t)v1.uv.u, v1.x, (int32_t)v2.uv.u, v2.x, 0x10'0000);
                                                                                       ^
/home/aho/DobieStation/src/core/gsthread.cpp:1574:87: error: missing terminating ' character
     int32_t pix_u_step = stepsize((int32_t)v1.uv.u, v1.x, (int32_t)v2.uv.u, v2.x, 0x10'0000);
                                                                                       ^~~~~~~
/home/aho/DobieStation/src/core/gsthread.cpp: In member function 'void GraphicsSynthesizerThread::render_sprite()':
/home/aho/DobieStation/src/core/gsthread.cpp:1573:5: error: expected ')' before 'float'
     float pix_s_step = stepsize(v1.s, v1.x, v2.s, v2.x, 0x10);
     ^~~~~
/home/aho/DobieStation/src/core/gsthread.cpp:1576:5: error: expected ')' before 'bool'
     bool tmp_tex = PRIM.texture_mapping;
     ^~~~
/home/aho/DobieStation/src/core/gsthread.cpp:1585:17: error: 'tmp_tex' was not declared in this scope
             if (tmp_tex)
                 ^~~~~~~
/home/aho/DobieStation/src/core/gsthread.cpp:1585:17: note: suggested alternative: 'tmp_uv'
             if (tmp_tex)
                 ^~~~~~~
                 tmp_uv
/home/aho/DobieStation/src/core/gsthread.cpp:1601:22: error: 'pix_s_step' was not declared in this scope
             pix_s += pix_s_step;
                      ^~~~~~~~~~
/home/aho/DobieStation/src/core/gsthread.cpp:1601:22: note: suggested alternative: 'pix_u_step'
             pix_s += pix_s_step;
                      ^~~~~~~~~~
                      pix_u_step
make[2]: *** [CMakeFiles/DobieStation.dir/build.make:674: CMakeFiles/DobieStation.dir/src/core/gsthread.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/DobieStation.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by ssk97** [comment]
Oops, this is my bad. The quote digit separator is a C++14 feature. You can remove the single quote in 0x10'0000 or use a C++14 compiler instead of the C++11 one.

All other errors are from that one.

**Comment by tokumeiwokiboushimasu** [comment]
ssk97, I made a pull request for using c++14.
PSI-Rockin, ssk97 made a pull request for removing quote separator.
You can choose whichever you like ;-)

**Comment by tokumeiwokiboushimasu** [comment]
Fixed.  Thanks.
